# Generated by Django 3.2.9 on 2021-12-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='text',
            field=models.TextField(max_length=1400),
        ),
    ]
