# Generated by Django 3.2.9 on 2021-11-23 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=150)),
                ('img', models.ImageField(upload_to='img')),
                ('number', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roel', models.CharField(choices=[('techer', 'techer'), ('student', 'student')], max_length=120)),
                ('last_name', models.CharField(max_length=200)),
                ('frst_name', models.CharField(max_length=200)),
                ('froms', models.ManyToManyField(to='courses.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Bookrecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_to', models.DateTimeField()),
                ('returnbook', models.DateTimeField(null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.user')),
            ],
        ),
    ]
