# Generated by Django 3.2.9 on 2021-11-23 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='froms',
            new_name='fovarid_book',
        ),
    ]
