# Generated by Django 3.2.9 on 2021-11-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_froms_user_fovarid_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fovarid_book',
            field=models.ManyToManyField(blank=True, null=True, to='courses.Book'),
        ),
    ]
