# Generated by Django 3.2.9 on 2021-11-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_book_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('fris_name', models.CharField(max_length=120)),
                ('science', models.CharField(choices=[('matematika', 'matematika'), ('informatika', 'informatika'), ('kimyo', 'kimyo'), ('onatili', 'onatili')], max_length=50)),
            ],
        ),
    ]
