# Generated by Django 3.2.9 on 2021-11-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrecord',
            name='returnbook',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
